coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 2%
    patch:
      default:
        target: 90%

comment:
  layout: "reach,diff,flags,components"
  behavior: default
  require_changes: true

ignore:
  - "src/platforms/**"
  - "src/index.ts"
  - "src/storage/adapters/deno-kv.ts"
  - "src/storage/adapters/supabase.ts"
